"""Path-integral control primitives and analytic verification oracles."""

from .action import brownian_log_likelihood, log_tilted_weight, path_action
from .controllers import (
    CEMAnchoredResidualControl,
    ConstantTwoDriverControl,
    LeanRBergomiControl,
    RBergomiTaskMode,
    SpectralDoobVolterraControl,
    TimePiecewiseTwoDriverControl,
    VFOBranchDiagnostics,
    VolterraFollmerOperator,
)
from .divergence import TiltedDivergenceDiagnostics, tilted_divergence_diagnostics
from .gaussian_excursion_oracle import (
    GaussianExcursionOracle,
    GaussianExcursionSample,
    GaussianExcursionSpec,
    build_gaussian_excursion_oracle,
    simulate_gaussian_excursion,
)
from .gaussian_mixture_oracle import (
    gaussian_single_drift_second_moment,
    gaussian_symmetric_mixture_log_q_over_p,
    gaussian_symmetric_mixture_second_moment,
    gaussian_two_tail_probability,
)
from .gaussian_oracles import (
    gaussian_exponential_tilt_log_normalizer,
    gaussian_exponential_tilt_optimal_control,
    gaussian_exponential_tilt_pi_gap,
    gaussian_exponential_tilt_pi_objective,
    gaussian_exponential_tilt_relative_variance,
    gaussian_left_tail_doob_drift,
    gaussian_left_tail_probability,
)
from .gaussian_smoothing import (
    DownsideThresholds,
    GaussianShiftDecomposition,
    decompose_gaussian_shift,
    downside_excursion_thresholds,
    orthogonal_gaussian_residual,
    positive_flat_direction,
    scaled_normal_cdf,
    scaled_normal_cdf_difference,
    signed_log_normal_cdf_difference,
    stable_normal_cdf_difference,
    validate_positive_unit_direction,
)
from .heston_oracle import (
    HestonLogDesirabilityGradient,
    HestonOracleControl,
    HestonOracleNumerics,
    heston_log_desirability_gradient,
    heston_soft_left_tail_desirability,
    heston_soft_oracle_control,
)
from .memory import SOEKernelBank, fit_positive_soe_kernel
from .mixture import (
    all_expert_log_q_over_p,
    log_mixture_q_over_p,
    sample_mixture_labels,
    selected_component_log_p_over_q,
)
from .path_functionals import DownsideExcursionTask
from .pice import ConstantPICEFit, fit_constant_pice, reconstruct_candidate_increments
from .potentials import terminal_left_tail_potential
from .rbergomi_branching import (
    BranchedCoupledRBergomiPaths,
    ConditionalVolterraBridgeCoefficients,
    RBergomiCoarseTrunks,
    conditional_volterra_bridge_coefficients,
    refine_rbergomi_coarse_trunks,
    sample_conditional_brownian_fine_pairs,
    sample_conditional_volterra_fine_innovations,
    sample_rbergomi_coarse_trunks,
    simulate_branched_rbergomi_adjacent,
    subset_rbergomi_coarse_trunks,
)
from .rbergomi_coupling import (
    AdjacentLocalGaussianCoefficients,
    CoupledRBergomiPaths,
    RBergomiLevelPaths,
    adjacent_local_gaussian_coefficients,
    simulate_coupled_rbergomi_adjacent,
)
from .rbergomi_fft import (
    AdjacentRBergomiFFTInnovations,
    BLPFFTKernel,
    RBergomiFFTInnovations,
    blp_fft_kernel,
    historical_volterra_convolution,
    simulate_coupled_rbergomi_adjacent_fft,
    simulate_rbergomi_fft,
)
from .rbergomi_mixture import (
    RBergomiMixtureSample,
    replay_rbergomi_control_on_target_paths,
    simulate_rbergomi_mixture,
)
from .rbergomi_multilevel import (
    CoupledRBergomiMixtureSample,
    simulate_coupled_rbergomi_mixture,
)
from .rbergomi_smoothing import (
    AffineRBergomiLogSpot,
    SmoothedAdjacentRBergomiEstimate,
    SmoothedRBergomiEstimate,
    SmoothedRBergomiLevel,
    affine_rbergomi_log_spot,
    evaluate_smoothed_adjacent_rbergomi_sample,
    evaluate_smoothed_rbergomi_sample,
    simulate_smoothed_adjacent_rbergomi,
    simulate_smoothed_rbergomi,
)

__all__ = [
    "ConstantPICEFit",
    "CEMAnchoredResidualControl",
    "ConstantTwoDriverControl",
    "DownsideExcursionTask",
    "GaussianExcursionOracle",
    "GaussianExcursionSample",
    "GaussianExcursionSpec",
    "LeanRBergomiControl",
    "RBergomiMixtureSample",
    "AdjacentLocalGaussianCoefficients",
    "BranchedCoupledRBergomiPaths",
    "ConditionalVolterraBridgeCoefficients",
    "CoupledRBergomiMixtureSample",
    "CoupledRBergomiPaths",
    "RBergomiLevelPaths",
    "RBergomiCoarseTrunks",
    "RBergomiTaskMode",
    "SpectralDoobVolterraControl",
    "TimePiecewiseTwoDriverControl",
    "TiltedDivergenceDiagnostics",
    "VFOBranchDiagnostics",
    "VolterraFollmerOperator",
    "HestonLogDesirabilityGradient",
    "HestonOracleControl",
    "HestonOracleNumerics",
    "brownian_log_likelihood",
    "build_gaussian_excursion_oracle",
    "fit_constant_pice",
    "gaussian_exponential_tilt_log_normalizer",
    "gaussian_exponential_tilt_optimal_control",
    "gaussian_exponential_tilt_pi_gap",
    "gaussian_exponential_tilt_pi_objective",
    "gaussian_exponential_tilt_relative_variance",
    "gaussian_left_tail_doob_drift",
    "gaussian_left_tail_probability",
    "log_tilted_weight",
    "heston_log_desirability_gradient",
    "heston_soft_left_tail_desirability",
    "heston_soft_oracle_control",
    "path_action",
    "reconstruct_candidate_increments",
    "replay_rbergomi_control_on_target_paths",
    "SOEKernelBank",
    "fit_positive_soe_kernel",
    "all_expert_log_q_over_p",
    "adjacent_local_gaussian_coefficients",
    "conditional_volterra_bridge_coefficients",
    "gaussian_single_drift_second_moment",
    "gaussian_symmetric_mixture_log_q_over_p",
    "gaussian_symmetric_mixture_second_moment",
    "gaussian_two_tail_probability",
    "log_mixture_q_over_p",
    "sample_mixture_labels",
    "selected_component_log_p_over_q",
    "simulate_gaussian_excursion",
    "simulate_rbergomi_mixture",
    "simulate_coupled_rbergomi_adjacent",
    "refine_rbergomi_coarse_trunks",
    "sample_conditional_brownian_fine_pairs",
    "sample_conditional_volterra_fine_innovations",
    "sample_rbergomi_coarse_trunks",
    "simulate_branched_rbergomi_adjacent",
    "subset_rbergomi_coarse_trunks",
    "simulate_coupled_rbergomi_mixture",
    "terminal_left_tail_potential",
    "tilted_divergence_diagnostics",
    "AdjacentRBergomiFFTInnovations",
    "AffineRBergomiLogSpot",
    "BLPFFTKernel",
    "DownsideThresholds",
    "GaussianShiftDecomposition",
    "RBergomiFFTInnovations",
    "SmoothedAdjacentRBergomiEstimate",
    "SmoothedRBergomiEstimate",
    "SmoothedRBergomiLevel",
    "affine_rbergomi_log_spot",
    "blp_fft_kernel",
    "decompose_gaussian_shift",
    "downside_excursion_thresholds",
    "evaluate_smoothed_adjacent_rbergomi_sample",
    "evaluate_smoothed_rbergomi_sample",
    "historical_volterra_convolution",
    "orthogonal_gaussian_residual",
    "positive_flat_direction",
    "scaled_normal_cdf",
    "scaled_normal_cdf_difference",
    "signed_log_normal_cdf_difference",
    "simulate_coupled_rbergomi_adjacent_fft",
    "simulate_rbergomi_fft",
    "simulate_smoothed_adjacent_rbergomi",
    "simulate_smoothed_rbergomi",
    "stable_normal_cdf_difference",
    "validate_positive_unit_direction",
]
