"""Training objectives and validated importance-sampling baselines.

See ``docs/formulation.md §3``.
"""

from .cem import (
    CEMBatch,
    CEMIteration,
    CEMResult,
    HestonTerminalLossSampler,
    fit_constant_control_cem,
)
from .heston_feedback import (
    FeedbackPICEObjective,
    FeedbackTrainingRecord,
    HardJ2Objective,
    HestonOracleDataset,
    OracleAlignment,
    SoftPIObjective,
    TwoDriverHestonControl,
    build_heston_oracle_dataset,
    candidate_log_density_on_target_paths,
    feedback_pice_objective,
    fit_heston_oracle_distillation,
    hard_j2_objective,
    load_two_driver_control_checkpoint,
    oracle_alignment,
    save_two_driver_control_checkpoint,
    soft_pi_objective,
    train_feedback_pice_stage,
    train_hard_j2_stage,
    train_soft_pi_stage,
    two_driver_control_state_sha256,
)
from .markov_control import (
    ArchitectureName,
    FeatureMapName,
    MarkovianHestonControl,
    MarkovObjectiveDiagnostics,
    MarkovTrainingEpoch,
    MarkovTrainingResult,
    load_markovian_control_checkpoint,
    markov_control_objective,
    markov_control_state_sha256,
    save_markovian_control_checkpoint,
    train_markovian_control,
)
from .objectives import (
    kl_regularized_objective,
    variance_minimization_objective,
)
from .vfo import (
    VFOHardJ2Objective,
    VFOObjectiveName,
    VFOPICEObjective,
    VFOSoftPIObjective,
    VFOTrainingRecord,
    replay_vfo_on_target_paths,
    train_vfo_stage,
    vfo_hard_j2_objective,
    vfo_pice_objective,
    vfo_soft_pi_objective,
)

__all__ = [
    "CEMBatch",
    "CEMIteration",
    "CEMResult",
    "HestonTerminalLossSampler",
    "FeedbackPICEObjective",
    "FeedbackTrainingRecord",
    "HardJ2Objective",
    "HestonOracleDataset",
    "fit_constant_control_cem",
    "MarkovianHestonControl",
    "ArchitectureName",
    "FeatureMapName",
    "MarkovObjectiveDiagnostics",
    "MarkovTrainingEpoch",
    "MarkovTrainingResult",
    "OracleAlignment",
    "SoftPIObjective",
    "TwoDriverHestonControl",
    "build_heston_oracle_dataset",
    "candidate_log_density_on_target_paths",
    "feedback_pice_objective",
    "fit_heston_oracle_distillation",
    "hard_j2_objective",
    "load_two_driver_control_checkpoint",
    "markov_control_state_sha256",
    "oracle_alignment",
    "save_two_driver_control_checkpoint",
    "save_markovian_control_checkpoint",
    "load_markovian_control_checkpoint",
    "markov_control_objective",
    "train_markovian_control",
    "soft_pi_objective",
    "train_feedback_pice_stage",
    "train_hard_j2_stage",
    "train_soft_pi_stage",
    "two_driver_control_state_sha256",
    "variance_minimization_objective",
    "kl_regularized_objective",
    "VFOHardJ2Objective",
    "VFOObjectiveName",
    "VFOPICEObjective",
    "VFOSoftPIObjective",
    "VFOTrainingRecord",
    "replay_vfo_on_target_paths",
    "train_vfo_stage",
    "vfo_hard_j2_objective",
    "vfo_pice_objective",
    "vfo_soft_pi_objective",
]
